baseURL = 'https://new.umbrella-plus.com.ua/'
title = 'Viva Plus'
relativeURLs = true
enableRobotsTXT = true
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.mounts]]
    source = "content/ru-lang"
    target = "content"
    lang = "ru"
[[module.mounts]]
    source = "content/ua-lang"
    target = "content"
    lang = "uk"
[[module.mounts]]
    source = "content/shared"
    target = "content"
    lang = "ru"
[[module.mounts]]
    source = "content/shared"
    target = "content"
    lang = "uk"


[languages]
    [languages.ru]
        contentDir = 'content/ru-lang'
        languageCode = 'ru-UA'
        languageName = 'RU'
        weight = 10
            [[languages.ru.menus.main]]
                name = 'Алкоголизм'
                weight = 10
                identifier = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Лечение алкоголизма'
                        pageRef = 'lechenie-alcogolizma'
                        weight = 10
                        parent = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Вывод из запоя'
                        pageRef = 'vivod-iz-zapoya'
                        weight = 20
                        parent = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Экстренный вызов нарколога'
                        pageRef = 'nargolog'
                        weight = 30
                        parent = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Капельница от алкоголя'
                        pageRef = 'kapelnitsya-ot-alkogolya'
                        weight = 40
                        parent = 'services'
                    [[languages.ru.menus.main]]
                        name = 'Лечение пивного алкоголизма'
                        pageRef = 'lechenie-pivnogo-alkogolizma'
                        weight = 50
                        parent = 'services'
            [[languages.ru.menus.main]]
                name = 'Наркомания'
                weight = 20
                identifier = 'narcology'
                    [[languages.ru.menus.main]]
                        name = 'Лечение наркомании'
                        pageRef = 'lechenie-narkomanii'
                        weight = 10
                        parent = 'narcology'
                    [[languages.ru.menus.main]]
                        name = 'Детоксикация от метадона'
                        pageRef = 'detox-metadon'
                        weight = 20
                        parent = 'narcology'
                    [[languages.ru.menus.main]]
                        name = 'Детоксикация от налбуфина'
                        pageRef = 'detox-nalbufin'
                        weight = 30
                        parent = 'narcology'
                    [[languages.ru.menus.main]]
                        name = 'Детоксикация от кокаина'
                        pageRef = 'detox-kokain'
                        weight = 40
                        parent = 'narcology'
                    [[languages.ru.menus.main]]
                        name = 'Детоксикация от лирики'
                        pageRef = 'detox-lirika'
                        weight = 50
                        parent = 'narcology'
            [[languages.ru.menus.main]]
                name = 'Кодирование'
                weight = 30
                identifier = 'kodirovanie'
                [[languages.ru.menus.main]]
                    name = 'Кодирование от алкоголизма таблетки Тетурам'
                    pageRef = 'kodirovanie-teturam'
                    weight = 10
                    parent = 'kodirovanie'
                [[languages.ru.menus.main]]
                    name = 'Кодирование от алкоголизма Капли Мидзо'
                    pageRef = 'kodirovanie-midzo'
                    weight = 20
                    parent = 'kodirovanie'
                [[languages.ru.menus.main]]
                    name = 'Кодирование от алкоголизма укол Дисульфирам'
                    pageRef = 'kodirovanie-disulfiram'
                    weight = 30
                    parent = 'kodirovanie'
            [[languages.ru.menus.main]]
                name = 'Филиалы'
                weight = 40
                pageRef = '#'
                identifier = 'filials'
                    [[languages.ru.menus.main]]
                        name = 'Харьков'
                        pageRef = 'kharkiv'
                        weight = 10
                        parent = 'filials'
            [[languages.ru.menus.main]]
                name = 'Дополнительно'
                weight = 60
                identifier = 'extra'
                    [[languages.ru.menus.main]]
                        name = 'О нас'
                        pageRef = '/about-us'
                        weight = 20
                        parent = 'extra'
                    [[languages.ru.menus.main]]
                        name = 'Сотрудничество'
                        pageRef = '/collaboration'
                        weight = 30
                        parent = 'extra'
                    [[languages.ru.menus.main]]
                        name = 'Отзывы'
                        url = '/reviews'
                        weight = 40
                        parent = 'extra'
    [languages.uk]
        contentDir = 'content/ua-lang'
        languageCode = 'uk-UA'
        languageName = 'UA'
        weight = 20
            [[languages.uk.menus.main]]
                name = 'Послуги'
                pageRef = '/services'
                weight = 10
            identifier = 'services'
                    [[languages.uk.menus.main]]
                        name = 'Лікування алкоголізму'
                        pageRef = '/services'
                        weight = 10
                        parent = 'services'
            [[languages.uk.menus.main]]
                name = 'Лікарі'
                url = '/uk/#doctors'
                weight = 20
                identifier = 'doctors'
            [[languages.uk.menus.main]]
                name = 'Блог'
                pageRef = '/blog'
                weight = 30
            [[languages.uk.menus.main]]
            name = 'Філіали'
            weight = 30
            identifier = 'filials'
                    [[languages.uk.menus.main]]
                        name = 'Харків'
                        pageRef = '/kharkiv'
                        weight = 10
                        parent = 'filials'
            [[languages.uk.menus.main]]
                name = 'Відгуки'
                url = '/uk/reviews'
                weight = 50
            [[languages.uk.menus.main]]
                name = 'Додатково'
                weight = 60
                identifier = 'extra'
                    [[languages.uk.menus.main]]
                        name = 'Про нас'
                        pageRef = '/about-us'
                        weight = 20
                        parent = 'extra'
                    [[languages.uk.menus.main]]
                        name = 'Співпраця'
                        pageRef = '/collaboration'
                        weight = 30
                        parent = 'extra'